import {
  CategoryInfo,
  DriverData,
  LeadCapture,
  ReferralRecord,
  CommercialAd,
  BroadcastNotification,
  DemandZoneHeatmap,
} from './types';

export const OFFICIAL_COLORS = {
  bg: '#000000',
  primary: '#A8E63A', // Verde Pera oficial
  primaryHover: '#95d130',
  white: '#FFFFFF',
  darkSurface: '#121212',
  darkCard: '#181818',
  darkBorder: '#282828',
  mutedText: '#A1A1AA',
};

export const CATEGORIES: CategoryInfo[] = [
  {
    id: 'w-bike',
    name: 'W-Bike',
    badge: '🚲 Entregas Leves & Curtas',
    icon: 'Bike',
    description: 'Tarifa Mínima R$ 10,00 até 1 km + R$ 1,00/km adicional. Ideal para documentos, malotes e pequenos pacotes.',
    basePrice: 10.0,
    perKmPrice: 1.0,
    capacity: '1 Volume (até 5kg)',
    etaMinutesBase: 4,
    allowsDeliveries: true,
    modalities: ['comum', 'contrato'],
  },
  {
    id: 'w-moto',
    name: 'W-Moto',
    badge: '🏍️ Rápido & Econômico',
    icon: 'Flame',
    description: 'Tarifa Mínima R$ 10,00 até 1 km + R$ 2,00/km adicional. Agilidade urbana no trânsito para 1 passageiro ou entrega expressa.',
    basePrice: 10.0,
    perKmPrice: 2.0,
    capacity: '1 Passageiro ou Encomenda',
    etaMinutesBase: 3,
    allowsDeliveries: true,
    modalities: ['comum', 'prime', 'contrato'],
  },
  {
    id: 'w-carro',
    name: 'W-Carro',
    badge: '🚗 Conforto, Ar & Espaço',
    icon: 'Car',
    description: 'Tarifa Mínima R$ 10,00 até 1 km + R$ 3,00/km adicional. Viagens com ar-condicionado obrigatório e motoristas credenciados.',
    basePrice: 10.0,
    perKmPrice: 3.0,
    capacity: 'Até 4 Passageiros',
    etaMinutesBase: 5,
    allowsDeliveries: true,
    modalities: ['comum', 'prime', 'contrato'],
  },
  {
    id: 'w-taxi',
    name: 'W-Táxi',
    badge: '🚕 Faixa Exclusiva & Taxímetro',
    icon: 'ShieldCheck',
    description: 'Tarifa Mínima R$ 10,00 até 1 km. Acima de 1 km, calculado conforme taxímetro oficial regulamentado pelo Inmetro.',
    basePrice: 10.0,
    perKmPrice: 0.0,
    capacity: 'Até 4 Passageiros',
    etaMinutesBase: 4,
    allowsDeliveries: true,
    isTaximeterOnly: true,
    modalities: ['comum', 'prime', 'contrato'],
  },
  {
    id: 'w-elas',
    name: 'W-Elas',
    badge: '🌸 Conduzido por Mulheres',
    icon: 'Sparkles',
    description: 'Tarifa Mínima R$ 10,00 até 1 km + R$ 3,20/km adicional. Exclusivo para passageiras mulheres com motoristas mulheres credenciadas.',
    basePrice: 10.0,
    perKmPrice: 3.2,
    capacity: 'Até 4 Passageiras',
    etaMinutesBase: 5,
    allowsDeliveries: false,
    modalities: ['comum', 'prime'],
  },
  {
    id: 'w-moto-entrega',
    name: 'W-Entregas Express',
    badge: '📦 Baú Térmico & Malotes',
    icon: 'Package',
    description: 'Tarifa Mínima R$ 10,00 até 1 km + R$ 2,00/km adicional. Entregas de até 10 kg com baú térmico seguro.',
    basePrice: 10.0,
    perKmPrice: 2.0,
    capacity: 'Até 10 kg (Baú 45L)',
    etaMinutesBase: 3,
    allowsDeliveries: true,
    modalities: ['comum', 'contrato'],
  },
];

export const COMMISSION_TIERS_INFO = [
  { range: 'R$ 10,00 a R$ 100,00', centralTax: 'R$ 3,00', rule: 'Comissão Central Fixa' },
  { range: 'R$ 100,01 a R$ 200,00', centralTax: 'R$ 7,00', rule: 'Comissão Central Fixa' },
  { range: 'R$ 200,01 a R$ 300,00', centralTax: 'R$ 30,00', rule: 'Comissão Central Fixa' },
  { range: 'R$ 300,01 a R$ 399,99', centralTax: 'R$ 40,00', rule: 'Comissão Central Fixa' },
  { range: 'R$ 400,00 ou mais', centralTax: 'R$ 70,00', rule: 'Teto Fixo Inviolável Central' },
];

export const AUDIO_SCRIPTS = {
  startRide:
    'Bem-vindo à W-DRIVER. A partir de agora esta viagem poderá ser registrada pelos recursos de segurança disponíveis na plataforma para proteção de passageiros e motoristas. Boa viagem. Quem escolhe preço corre riscos. Quem escolhe a W-DRIVER escolhe chegar bem!',
  endRide:
    'Chegamos ao seu destino. A W-DRIVER agradece a sua preferência. Até a próxima.',
  driverArrived:
    'O seu motorista W-DRIVER chegou ao local de embarque. O tempo de espera oficial de 3 minutos foi iniciado.',
  waitExpired:
    'Tempo de espera encerrado.',
};

export const INITIAL_REFERRALS: ReferralRecord[] = [
  {
    id: 'ref-1',
    referrerCode: 'W0701',
    referredName: 'Carlos Eduardo Santana',
    referredType: 'passenger',
    completedRides: 5,
    targetRides: 5,
    bonusEarned: 5.0,
    isPaid: true,
    date: '14/08/2026',
  },
  {
    id: 'ref-2',
    referrerCode: 'W0701',
    referredName: 'Mariana Duarte Souza',
    referredType: 'motoboy',
    completedRides: 5,
    targetRides: 5,
    bonusEarned: 5.0,
    isPaid: true,
    date: '15/08/2026',
  },
  {
    id: 'ref-3',
    referrerCode: 'W0701',
    referredName: 'Felipe Albuquerque',
    referredType: 'driver',
    completedRides: 3,
    targetRides: 5,
    bonusEarned: 0.0,
    isPaid: false,
    date: '17/08/2026',
  },
  {
    id: 'ref-4',
    referrerCode: 'W0701',
    referredName: 'Juliana Medeiros',
    referredType: 'biker',
    completedRides: 4,
    targetRides: 5,
    bonusEarned: 0.0,
    isPaid: false,
    date: '18/08/2026',
  },
];

// Official Initial Drivers with Full CEO Verification & Inspection Data
export const INITIAL_DRIVERS: DriverData[] = [
  {
    id: 'drv-1',
    name: 'Marcos Vinícius Silva',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    isFaceVerified: true,
    phone: '(83) 99874-1234',
    rating: 4.98,
    totalTrips: 1842,
    category: 'w-carro',
    vehicleModel: 'Toyota Corolla Cross Híbrido',
    vehiclePlate: 'WDR-2026',
    vehicleColor: 'Prata Metálico',
    lat: -7.11532,
    lng: -34.861,
    heading: 45,
    isOnline: true,
    isBusy: false,
    acceptsPassengers: true,
    acceptsDeliveries: true,
    accountStatus: 'active',
    inspectionStatus: 'approved',
    inspectionDate: '10/08/2026',
    criminalBackgroundChecked: true,
    vehicleInspected: true,
  },
  {
    id: 'drv-2',
    name: 'Rodrigo Alencar',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    isFaceVerified: true,
    phone: '(83) 99123-5566',
    rating: 4.95,
    totalTrips: 920,
    category: 'w-moto',
    vehicleModel: 'Honda CB 300F Twister',
    vehiclePlate: 'MOT-0701',
    vehicleColor: 'Preto Fosco',
    lat: -7.119,
    lng: -34.858,
    heading: 120,
    isOnline: true,
    isBusy: false,
    acceptsPassengers: true,
    acceptsDeliveries: true,
    accountStatus: 'active',
    inspectionStatus: 'approved',
    inspectionDate: '08/08/2026',
    criminalBackgroundChecked: true,
    vehicleInspected: true,
  },
  {
    id: 'drv-3',
    name: 'Lucas Ferreira',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    isFaceVerified: true,
    phone: '(83) 98844-3322',
    rating: 5.0,
    totalTrips: 410,
    category: 'w-bike',
    vehicleModel: 'Caloi Elite Carbon Pro (Bag Térmica)',
    vehiclePlate: 'W-BIKE #04',
    vehicleColor: 'Verde Pera W-DRIVER',
    lat: -7.112,
    lng: -34.863,
    heading: 90,
    isOnline: true,
    isBusy: false,
    acceptsPassengers: false,
    acceptsDeliveries: true,
    accountStatus: 'active',
    inspectionStatus: 'approved',
    inspectionDate: '12/08/2026',
    criminalBackgroundChecked: true,
    vehicleInspected: true,
  },
  {
    id: 'drv-4',
    name: 'José Valério Medeiros',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    isFaceVerified: true,
    phone: '(83) 99988-7711',
    rating: 4.96,
    totalTrips: 3410,
    category: 'w-taxi',
    vehicleModel: 'Chevrolet Spin 7 Lugares',
    vehiclePlate: 'TXI-9840',
    vehicleColor: 'Branco Oficial',
    lat: -7.1175,
    lng: -34.865,
    heading: 270,
    isOnline: true,
    isBusy: false,
    acceptsPassengers: true,
    acceptsDeliveries: true,
    accountStatus: 'active',
    inspectionStatus: 'approved',
    inspectionDate: '01/08/2026',
    criminalBackgroundChecked: true,
    vehicleInspected: true,
  },
  {
    id: 'drv-5',
    name: 'Gabriel Costa Express',
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    isFaceVerified: true,
    phone: '(83) 98777-6655',
    rating: 4.99,
    totalTrips: 1120,
    category: 'w-moto-entrega',
    vehicleModel: 'Yamaha Fazer 250 (Baú 45L)',
    vehiclePlate: 'ENT-2026',
    vehicleColor: 'Preto & Verde W',
    lat: -7.114,
    lng: -34.855,
    heading: 180,
    isOnline: true,
    isBusy: false,
    acceptsPassengers: false,
    acceptsDeliveries: true,
    accountStatus: 'active',
    inspectionStatus: 'approved',
    inspectionDate: '05/08/2026',
    criminalBackgroundChecked: true,
    vehicleInspected: true,
  },
  // Drivers Aguardando Vistoria e Homologação do CEO
  {
    id: 'drv-6',
    name: 'Anderson Cavalcanti',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    isFaceVerified: true,
    phone: '(83) 99344-9988',
    rating: 5.0,
    totalTrips: 0,
    category: 'w-carro',
    vehicleModel: 'Hyundai HB20S Comfort Plus',
    vehiclePlate: 'WAP-8822',
    vehicleColor: 'Cinza Titanium',
    lat: -7.125,
    lng: -34.87,
    heading: 0,
    isOnline: false,
    isBusy: false,
    acceptsPassengers: true,
    acceptsDeliveries: true,
    accountStatus: 'pending_approval',
    inspectionStatus: 'pending',
    criminalBackgroundChecked: true,
    vehicleInspected: false,
  },
  {
    id: 'drv-7',
    name: 'Leandro Vasconcelos',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    isFaceVerified: true,
    phone: '(83) 98822-1100',
    rating: 5.0,
    totalTrips: 0,
    category: 'w-moto',
    vehicleModel: 'Honda CG 160 Titan',
    vehiclePlate: 'MOT-4411',
    vehicleColor: 'Vermelho Perolizado',
    lat: -7.108,
    lng: -34.845,
    heading: 60,
    isOnline: false,
    isBusy: false,
    acceptsPassengers: true,
    acceptsDeliveries: true,
    accountStatus: 'pending_approval',
    inspectionStatus: 'scheduled',
    inspectionDate: '19/08/2026 às 15:00',
    criminalBackgroundChecked: true,
    vehicleInspected: false,
  },
];

// Local Commercial Partners & Banners for Passenger Carousel & Monetization
export const INITIAL_COMMERCIAL_ADS: CommercialAd[] = [
  {
    id: 'ad-1',
    partnerName: 'Espetinho do Gaúcho & Brasa Viva',
    segment: 'Churrasco & Espetinhos',
    categoryTag: 'espetinho',
    title: '🍢 Espetinho do Gaúcho • O Melhor Churrasco!',
    description: 'Espetinhos na brasa, acompanhamentos completos, cerveja trincando e música boa. Ganhe 10% OFF com W Drive.',
    bannerUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80',
    actionText: 'Pedir Corrida até o Espetinho',
    discountCoupon: 'ESPETO10',
    address: 'Av. Almirante Barroso, 340 - Centro',
    phoneWhatsApp: '(83) 99811-2233',
    rating: 4.9,
    coordinates: { lat: -7.118, lng: -34.862 },
    displayDurationSeconds: 6,
    isActive: true,
    position: 'both',
    viewsCount: 4280,
    clicksCount: 312,
  },
  {
    id: 'ad-2',
    partnerName: 'Sorveteria & Açaí Tropical Prime',
    segment: 'Sorvetes, Açaí & Picolés',
    categoryTag: 'sorveteria',
    title: '🍦 Sorveteria Tropical • Açaí e Sorvetes Artesanais',
    description: 'Mais de 40 sabores de sorvetes artesanais, taças gourmet e açaí com adicionais ilimitados. Desconto VIP para passageiros!',
    bannerUrl: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=600&auto=format&fit=crop&q=80',
    actionText: 'Ir até a Sorveteria',
    discountCoupon: 'SORVETE15',
    address: 'Av. Epitácio Pessoa, 1140 - Tambaú',
    phoneWhatsApp: '(83) 99144-8899',
    rating: 5.0,
    coordinates: { lat: -7.112, lng: -34.855 },
    displayDurationSeconds: 6,
    isActive: true,
    position: 'both',
    viewsCount: 3890,
    clicksCount: 295,
  },
  {
    id: 'ad-3',
    partnerName: 'Drogaria São Lucas / FarmaW 24h',
    segment: 'Saúde & Farmácia 24h',
    categoryTag: 'farmacia',
    title: '💊 Drogaria São Lucas • Medicamentos & Plantão 24h',
    description: 'Remédios, genéricos com até 50% de desconto e conveniência. Entrega expressa ou vá com seu motorista W Drive com total segurança.',
    bannerUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&auto=format&fit=crop&q=80',
    actionText: 'Pedir Medicamentos no WhatsApp',
    discountCoupon: 'FARMAW20',
    address: 'Rua dos Bancários, 89 - Bancários',
    phoneWhatsApp: '(83) 98877-4400',
    rating: 4.95,
    coordinates: { lat: -7.125, lng: -34.869 },
    displayDurationSeconds: 6,
    isActive: true,
    position: 'both',
    viewsCount: 1980,
    clicksCount: 140,
  },
  {
    id: 'ad-4',
    partnerName: 'Hamburgueria Artesanal W-Burger',
    segment: 'Smash Burgers & Batatas',
    categoryTag: 'hamburgueria',
    title: '🍔 W-Burger • O Smash Mais Suculento da Cidade',
    description: 'Pão brioche selado na manteiga, blend Angus 160g e molho especial da casa. Ganhe batata frita grátis com o cupom.',
    bannerUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    actionText: 'Ir até a Hamburgueria',
    discountCoupon: 'WBURGER',
    address: 'Av. Manaíra, 560 - Manaíra',
    phoneWhatsApp: '(83) 99655-1212',
    rating: 4.88,
    coordinates: { lat: -7.108, lng: -34.848 },
    displayDurationSeconds: 6,
    isActive: true,
    position: 'both',
    viewsCount: 3410,
    clicksCount: 260,
  },
  {
    id: 'ad-5',
    partnerName: 'Pizzaria Forno a Lenha Bella Massa',
    segment: 'Pizzas Artesanais',
    categoryTag: 'pizzaria',
    title: '🍕 Pizzaria Bella Massa • Forno a Lenha Tradicional',
    description: 'Massa crocante com fermentação natural de 48h. Borda recheada grátis para passageiros e motoristas W Drive!',
    bannerUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    actionText: 'Pedir com Borda Grátis',
    discountCoupon: 'BELLA10',
    address: 'Rua dos Navegantes, 240 - Tambaú',
    phoneWhatsApp: '(83) 98700-3344',
    rating: 4.92,
    coordinates: { lat: -7.116, lng: -34.852 },
    displayDurationSeconds: 6,
    isActive: true,
    position: 'both',
    viewsCount: 3120,
    clicksCount: 228,
  },
  {
    id: 'ad-6',
    partnerName: 'Auto Center & Lava Jato Express W',
    segment: 'Mecânica, Troca de Óleo & Estética',
    categoryTag: 'geral',
    title: '🔧 Auto Center Express • Especial Frota & Parceiros',
    description: 'Alinhamento 3D, balanceamento, troca de óleo e higienização com 20% de desconto oficial.',
    bannerUrl: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=600&auto=format&fit=crop&q=80',
    actionText: 'Agendar Revisão Rápida',
    discountCoupon: 'WPARCEIRO20',
    address: 'Av. Cruz das Armas, 980 - Cruz das Armas',
    phoneWhatsApp: '(83) 99111-7788',
    rating: 4.85,
    coordinates: { lat: -7.135, lng: -34.885 },
    displayDurationSeconds: 7,
    isActive: true,
    position: 'both',
    viewsCount: 2150,
    clicksCount: 164,
  },
];

// Initial Push Broadcast Notifications Sent by Central Master CEO
export const INITIAL_BROADCAST_MESSAGES: BroadcastNotification[] = [
  {
    id: 'msg-1',
    title: '🚗 Bônus de Alta Demanda Ativado no Fim de Semana!',
    message: 'Motoristas e motociclistas parceiros: adicionamos bônus de R$ 5,00 por corrida na Orla e Polo Gastronômico.',
    channel: 'drivers',
    urgency: 'high',
    sentAt: '18/08/2026 às 18:30',
    sender: 'CEO Central W-DRIVER',
    readByCount: 42,
  },
  {
    id: 'msg-2',
    title: '⭐ Vistoria Presencial e Credenciamento Oficial',
    message: 'A segurança é nosso maior pilar. Todos os veículos da W-DRIVER contam com vistoria e verificação de antecedentes.',
    channel: 'all',
    urgency: 'normal',
    sentAt: '17/08/2026 às 10:00',
    sender: 'Central W-DRIVER',
    readByCount: 189,
  },
  {
    id: 'msg-3',
    title: '🍕 Parceria Exclusiva: Pizzaria do Maurício',
    message: 'Passageiros W-DRIVER ganham borda recheada grátis com o cupom WPIZZA nos parceiros credenciados.',
    channel: 'passengers',
    urgency: 'normal',
    sentAt: '16/08/2026 às 19:15',
    sender: 'Comercial W-DRIVER',
    readByCount: 110,
  },
];

// Real High-Demand Heatmap Zones & Peak Hours Analysis
export const INITIAL_HEATMAP_ZONES: DemandZoneHeatmap[] = [
  {
    id: 'zone-1',
    zoneName: 'Orla de Tambaú & Cabo Branco',
    city: 'João Pessoa',
    neighborhood: 'Tambaú / Cabo Branco',
    heatLevel: 'extreme',
    score: 96,
    activeRequests: 18,
    availableDrivers: 6,
    peakHours: '18:00 - 02:00 (Noturno & Fim de Semana)',
    centerCoordinates: { lat: -7.115, lng: -34.825 },
  },
  {
    id: 'zone-2',
    zoneName: 'Centro Comercial & Financeiro',
    city: 'João Pessoa',
    neighborhood: 'Centro Histórico',
    heatLevel: 'high',
    score: 88,
    activeRequests: 14,
    availableDrivers: 5,
    peakHours: '07:30 - 09:30 & 17:00 - 19:30',
    centerCoordinates: { lat: -7.118, lng: -34.885 },
  },
  {
    id: 'zone-3',
    zoneName: 'Polo Universitário & Castelo Branco',
    city: 'João Pessoa',
    neighborhood: 'Castelo Branco / UFPB',
    heatLevel: 'high',
    score: 84,
    activeRequests: 11,
    availableDrivers: 4,
    peakHours: '06:45 - 08:30 & 21:30 - 22:45',
    centerCoordinates: { lat: -7.142, lng: -34.848 },
  },
  {
    id: 'zone-4',
    zoneName: 'Shopping Manaíra & Bessa Mall',
    city: 'João Pessoa',
    neighborhood: 'Manaíra / Bessa',
    heatLevel: 'extreme',
    score: 93,
    activeRequests: 16,
    availableDrivers: 7,
    peakHours: '12:00 - 14:30 & 19:00 - 22:30',
    centerCoordinates: { lat: -7.098, lng: -34.847 },
  },
  {
    id: 'zone-5',
    zoneName: 'Aeroporto Castro Pinto & Terminal Rodoviário',
    city: 'Bayeux / João Pessoa',
    neighborhood: 'Aeroporto',
    heatLevel: 'moderate',
    score: 79,
    activeRequests: 8,
    availableDrivers: 4,
    peakHours: 'Voos matutinos (04h-07h) & noturnos (22h-01h)',
    centerCoordinates: { lat: -7.148, lng: -34.95 },
  },
];

export const BRAZILIAN_STATES = [
  { uf: 'PB', name: 'Paraíba' },
  { uf: 'PE', name: 'Pernambuco' },
  { uf: 'RN', name: 'Rio Grande do Norte' },
  { uf: 'CE', name: 'Ceará' },
  { uf: 'AL', name: 'Alagoas' },
  { uf: 'BA', name: 'Bahia' },
  { uf: 'SE', name: 'Sergipe' },
  { uf: 'MA', name: 'Maranhão' },
  { uf: 'PI', name: 'Piauí' },
  { uf: 'SP', name: 'São Paulo' },
  { uf: 'RJ', name: 'Rio de Janeiro' },
  { uf: 'MG', name: 'Minas Gerais' },
  { uf: 'ES', name: 'Espírito Santo' },
  { uf: 'PR', name: 'Paraná' },
  { uf: 'SC', name: 'Santa Catarina' },
  { uf: 'RS', name: 'Rio Grande do Sul' },
  { uf: 'DF', name: 'Distrito Federal' },
  { uf: 'GO', name: 'Goiás' },
  { uf: 'MT', name: 'Mato Grosso' },
  { uf: 'MS', name: 'Mato Grosso do Sul' },
  { uf: 'AM', name: 'Amazonas' },
  { uf: 'PA', name: 'Pará' },
  { uf: 'RO', name: 'Rondônia' },
  { uf: 'AC', name: 'Acre' },
  { uf: 'AP', name: 'Amapá' },
  { uf: 'RR', name: 'Roraima' },
  { uf: 'TO', name: 'Tocantins' },
];

export const INITIAL_CAPTURED_LEADS: LeadCapture[] = [
  {
    id: 'lead-01',
    name: 'Dra. Renata Albuquerque',
    email: 'renata.albuquerque@gmail.com',
    phone: '(83) 98838-1869',
    cpf: '054.321.890-44',
    city: 'João Pessoa - PB',
    birthState: 'PB',
    residenceState: 'PB',
    isOutOfState: false,
    type: 'passenger',
    status: 'pending_approval',
    referralCodeUsed: 'W0701',
    createdAt: 'Hoje às 09:15',
  },
  {
    id: 'lead-02',
    name: 'Marcos Vinicius Silva',
    email: 'marcos.vinicius.w@gmail.com',
    phone: '(83) 99683-0050',
    cpf: '123.456.789-00',
    cnhNumber: '06789123456 (EAR Ativa)',
    city: 'João Pessoa - PB',
    birthState: 'SP',
    residenceState: 'PB',
    isOutOfState: true,
    criminalCertFederal: true,
    criminalCertOriginState: true,
    criminalCertResidenceState: true,
    cnhEarAttached: true,
    crlvAttached: true,
    residenceProofAttached: true,
    profilePhotoAttached: true,
    secondStageMethod: 'residence',
    secondStageAddress: 'Rua Bancário Sérgio Guerra, 450 - Apt 302, Bancários, João Pessoa - PB',
    secondStageDate: 'Amanhã às 14:30',
    secondStageRepresentative: 'Wallace Soares (Representante Legal Oficial)',
    secondStageStatus: 'scheduled',
    type: 'driver',
    status: 'pending_approval',
    vehicleDetails: 'Toyota Corolla GLi 2.0 Flex • Placa: WDR-2026',
    createdAt: 'Hoje às 08:30',
  },
  {
    id: 'lead-03',
    name: 'Thiago Henrique Pontes',
    email: 'thiago.motoboy@gmail.com',
    phone: '(83) 98777-1122',
    cpf: '987.654.321-11',
    city: 'João Pessoa - PB',
    birthState: 'PB',
    residenceState: 'PB',
    isOutOfState: false,
    criminalCertFederal: true,
    criminalCertResidenceState: true,
    cnhEarAttached: true,
    crlvAttached: true,
    residenceProofAttached: true,
    profilePhotoAttached: true,
    secondStageMethod: 'residence',
    secondStageAddress: 'Av. Argemiro de Figueiredo, 1850 - Apt 401, Bessa, João Pessoa - PB',
    secondStageDate: 'Hoje às 16:00',
    secondStageRepresentative: 'Wallace Soares (Representante Legal Oficial)',
    secondStageStatus: 'data_collected',
    type: 'motoboy',
    status: 'pending_approval',
    vehicleDetails: 'Honda CG 160 Fan ESDI • Placa: MOT-4488',
    createdAt: 'Ontem às 18:20',
  },
  {
    id: 'lead-04',
    name: 'TechNordeste Logística & TI (Roberto Dias)',
    email: 'comercial@technordeste.com.br',
    phone: '(83) 98117-9524',
    cpf: '321.654.987-00',
    companyCnpj: '12.345.678/0001-90',
    contractNotes: 'Empresa corporativa com 35 colaboradores portando crachá de identificação',
    city: 'João Pessoa - PB',
    birthState: 'PB',
    residenceState: 'PB',
    isOutOfState: false,
    type: 'driver',
    status: 'pending_approval',
    createdAt: 'Ontem às 16:40',
  },
  {
    id: 'lead-05',
    name: 'Juliana Medeiros de Souza',
    email: 'juliana.medeiros@gmail.com',
    phone: '(83) 99122-3344',
    cpf: '887.665.443-22',
    city: 'João Pessoa - PB',
    birthState: 'RN',
    residenceState: 'PB',
    isOutOfState: true,
    type: 'passenger',
    status: 'active',
    referralCodeUsed: 'W0701',
    createdAt: '18/08/2026',
  },
];

export const POPULAR_DESTINATIONS = [
  {
    name: 'Avenida Epitácio Pessoa, 1500',
    neighborhood: 'Tambauzinho',
    city: 'João Pessoa',
    state: 'PB',
    lat: -7.1215,
    lng: -34.8612,
  },
  {
    name: 'Avenida Cabo Branco, 2200',
    neighborhood: 'Cabo Branco',
    city: 'João Pessoa',
    state: 'PB',
    lat: -7.135,
    lng: -34.825,
  },
  {
    name: 'Avenida Beira Rio, 850',
    neighborhood: 'Torre',
    city: 'João Pessoa',
    state: 'PB',
    lat: -7.126,
    lng: -34.872,
  },
  {
    name: 'Rua João Machado, 420',
    neighborhood: 'Centro Histórico',
    city: 'João Pessoa',
    state: 'PB',
    lat: -7.118,
    lng: -34.885,
  },
  {
    name: 'Rua João Câncio, 700',
    neighborhood: 'Manaíra',
    city: 'João Pessoa',
    state: 'PB',
    lat: -7.108,
    lng: -34.838,
  },
  {
    name: 'Shopping Manaíra (Av. Flávio Ribeiro Coutinho)',
    neighborhood: 'Manaíra',
    city: 'João Pessoa',
    state: 'PB',
    lat: -7.098,
    lng: -34.847,
  },
];
